const courses = [
    {
        "_id": "1",
        "name": "React",
        "description": "React is a JavaScript library for building user interfaces.Well assume that you have some familiarity with HTML and JavaScript, but you should be able to follow along even if youre coming from a different programming language. We ll also assume that youre familiar with programming concepts like functions, objects, arrays, and to a lesser extent, classes.",
        "image": "https://static.guvi.in/course-thumbnail/webps/python.webp",
        "duration": "11 hours",
        "price" : 499,
        "rating":4.1,
        "numReviews"  : 12,
         "enrolledstudents" : 1000,
    },
    {
        "_id": "2",
        "name": "Angular 2",
        "description": "Angular is a JavaScript library for building user interfaces",
        "image": "https://static.guvi.in/course-thumbnail/webps/python.webp",
        "duration": "11 hours",
        "price" : 499,
        "rating":2.1,
        "numReviews"  : 12,
         "enrolledstudents" : 1000,
    },
    {
        "_id": "3",
        "name": "Next.Js",
        "description": "Angular is a JavaScript library for building user interfaces",
        "image": "https://static.guvi.in/course-thumbnail/webps/python.webp",
        "duration": "11 hours",
        "price" : 499,
        "rating":4.1,
        "numReviews"  : 12,
         "enrolledstudents" : 1000,
    },
    {
        "_id": "4",
        "name": "Python",
        "description": "Angular is a JavaScript library for building user interfaces",
        "image": "https://static.guvi.in/course-thumbnail/webps/python.webp",
        "duration": "11 hours",
        "price" : 499,
        "rating": 2.5,
        "numReviews"  : 12,
         "enrolledstudents" : 1000,
    },
    {
        "_id": "5",
        "name": "Java",
        "description": "Angular is a JavaScript library for building user interfaces",
        "image": "https://static.guvi.in/course-thumbnail/webps/python.webp",
        "duration": "11 hours",
        "price" : 899,
        "rating":3.5,
        "numReviews": 90,
         "enrolledstudents" : 1000,
    }
]

export default courses;